## To use this makefile you will need to define the following env variables:
## ACL2:              : path to ACL2 executable
## ACL2_SYSTEM_BOOKS  : path to ACL2 system books directory

include $(ACL2_SYSTEM_BOOKS)/Makefile-generic

BOOKS = stmt stmt-modular
