#!/bin/sh

krun --compiled-def wcet-original-kompiled --main-module WCET -cTIMING="add |-> 1 sub |-> 1 mul |-> 1 div |-> 1 or |-> 1 and |-> 1 not |-> 1 load |-> 10 store |-> 10 jmp |-> 1 beq |-> 2 bne |-> 2 blt |-> 2 ble |-> 2 halt |-> 1 read |-> 3 write |-> 3 'rw(.KList) |-> 6 int |-> 2 rfi |-> 2" "$@"
